export default {
  languages: ["Java", "JavaScript", "C++", "C", "Swift"],
  web: [
    "Node.js",
    "React",
    "Angular",
    "Vue",
    "Redux",
    "Express",
    "GraphQL",
    "HTML",
    "CSS",
    "SCSS/SASS",
  ],
  tools: [
    "Git",
    "Docker",
    "AWS",
    "DigitalOcean",
    "Firebase",
    "Jenkins",
    "Mocha",
    "Jest",
    "Enzyme",
  ],
  databases: ["MySQL", "PostgreSQL", "MongoDB"],
  mobile: ["UIKit"],
}
